language: generic

arch:
  - amd64

services:
  - docker

_build_and_push: &build_and_push
  script:
    - docker build -t "$DOCKER_TAG" "$RELATIVE_PATH"
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin && docker push "$DOCKER_TAG"

jobs:
  include:
    - stage: Build vnc:base
      env:
        - DOCKER_TAG=bxggs/vnc:base RELATIVE_PATH=base
      <<: *build_and_push
    - stage: Build vnc:openbox
      env:
        - DOCKER_TAG=bxggs/vnc:openbox RELATIVE_PATH=openbox
      <<: *build_and_push
