name: Build and push Docker images
on:
  push:
    branches:
     - master
jobs:
  base-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t bxggs/vnc:base base
      - run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - run: docker push bxggs/vnc:base
  de-images:
    needs: base-image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name:
          - openbox
          - i3-gaps
          - xfce4
          - wmaker
        include:
          - name: openbox
            DOCKER_TAG: bxggs/vnc:openbox
            RELATIVE_PATH: openbox
          - name: i3-gaps
            DOCKER_TAG: bxggs/vnc:i3-gaps
            RELATIVE_PATH: i3-gaps
          - name: xfce4
            DOCKER_TAG: bxggs/vnc:xfce4
            RELATIVE_PATH: xfce4
          - name: wmaker
            DOCKER_TAG: bxggs/vnc:wmaker
            RELATIVE_PATH: wmaker
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t "${{ matrix.DOCKER_TAG }}" "${{ matrix.RELATIVE_PATH }}"
      - run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - run: docker push "${{ matrix.DOCKER_TAG }}"
