name: Build and push Docker images
on:
  push:
    branches:
     - master
jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t bxggs/vnc:base base
      - run: docker build -t bxggs/vnc:openbox openbox
      - run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - run: docker push bxggs/vnc:base
      - run: docker push bxggs/vnc:openbox
