name: Build and push Docker image
on:
  push:
    branches:
     - master
  pull_request:
    branches:
      - master
jobs:
  build-and-push-base-image:
    runs-on: ubuntu-latest
    env:
      DOCKER_TAG: bxggs/vnc:base
      RELATIVE_PATH: base
    steps:
      - uses: actions/checkout@v2
      - name: Build base image
        run: docker build -t "$DOCKER_TAG" "$RELATIVE_PATH"
      - name: Login to registry and push image
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push "$DOCKER_TAG"
